# Generated by Django 3.2.18 on 2023-03-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='memo_text',
            field=models.CharField(max_length=250),
        ),
    ]
